name = "cloudflare-agent"
main = "src/index.ts"
compatibility_date = "2024-10-15"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "cloudflare-agent-dev"

[env.staging]
name = "cloudflare-agent-staging"

[env.production]
name = "cloudflare-agent-prod"

# AI binding for Cloudflare AI models
[ai]
binding = "AI"

# KV namespace for rate limiting and caching
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# D1 database for conversation history
[[d1_databases]]
binding = "DB"
database_name = "agent-conversations"
database_id = "your-d1-database-id"

# Environment variables
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"
RATE_LIMIT_PER_MINUTE = "60"
MAX_CONVERSATION_HISTORY = "50"

# Secrets (set via wrangler secret put)
# CONTEXT7_API_KEY
# ANTHROPIC_API_KEY (if using external AI)

[build]
command = "npm run build"