name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claudecode')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claudecode')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claudecode')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claudecode') || contains(github.event.issue.title, '@claudecode')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      actions: read
      id-token: write
    steps:
      - name: Add initial reaction
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          trigger_phrase: "@claudcode"
          label_trigger: "claudecode"
          # Pass the conflict resolution prompt directly
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args: |
            --max-turns 15
            --system-prompt "You are an expert coder with a hacker MVP metality. Ensure the code remains functional changes and Always verify your changes before pushing with tests and formatting."
            --allowedTools "WebSearch,WebFetch,Edit,MultiEdit,Write,Read,Glob,Grep,LS,Bash(git:*),Bash(bun:*),Bash(npm:*),Bash(npx:*),Bash(gh:*)"
            
